//! store — the app's persistence: a single SQLite file in the data folder, versioned
//! schema. Writes exclusively to its own file; it doesn't even know the game's saves
//! exist. The frontend never touches disk itself: it goes through here via `ipc`.

mod migrations;

use std::path::Path;

use ipc::{Goal, GoalId, TargetKey};
use rusqlite::{params, Connection, OptionalExtension};

pub use migrations::SCHEMA_VERSION;

#[derive(Debug)]
pub enum StoreError {
    /// The file won't open, isn't SQLite, or a query failed.
    Unreadable { reason: String },
    /// The file was written by a newer version of the app.
    NewerSchema { found: u32, supported: u32 },
}

/// The result of `goals()`: a row whose target doesn't parse doesn't hide the others.
/// The id is its own column and always reads, so the UI can name it.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct GoalsRead {
    pub goals: Vec<Goal>,
    pub unreadable: Vec<GoalId>,
}

impl StoreError {
    fn from_sqlite(e: rusqlite::Error) -> StoreError {
        StoreError::Unreadable {
            reason: e.to_string(),
        }
    }
}

pub struct Store {
    conn: Connection,
}

// A derived `Debug` would expose the file path: `Connection` prints it in its own
// `Debug` (`.field("path", &self.path())`), and under the data folder that contains the
// Windows username. So, no field to show.
impl std::fmt::Debug for Store {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Store").finish_non_exhaustive()
    }
}

impl Store {
    /// Opens (or creates) the file and brings it to the current schema version.
    pub fn open(path: &Path) -> Result<Store, StoreError> {
        let conn = Connection::open(path).map_err(StoreError::from_sqlite)?;
        // A file that isn't SQLite fails here, on the first query, not on open.
        let found = migrations::current_version(&conn)?;
        migrations::apply(&conn, found)?;
        Ok(Store { conn })
    }

    pub fn schema_version(&self) -> Result<u32, StoreError> {
        migrations::current_version(&self.conn)
    }

    /// Goals in the order they were added. `Err` only if the query itself fails: an
    /// unreadable row ends up in `unreadable`, it doesn't wipe out the plan.
    ///
    /// `target_json` is the JSON of `ipc::TargetKey`, the on-disk format: see its own
    /// doc. Name and icon don't live in the file, they're resolved from the catalog on
    /// every read.
    pub fn goals(&self) -> Result<GoalsRead, StoreError> {
        let mut stmt = self
            .conn
            .prepare("SELECT id, target_json, created_unix, note FROM goals ORDER BY seq")
            .map_err(StoreError::from_sqlite)?;
        let rows = stmt
            .query_map([], |r| {
                Ok((
                    r.get::<_, String>(0)?,
                    r.get::<_, String>(1)?,
                    r.get::<_, i64>(2)?,
                    r.get::<_, Option<String>>(3)?,
                ))
            })
            .map_err(StoreError::from_sqlite)?;
        let mut out = GoalsRead::default();
        for row in rows {
            let (id, target_json, created_unix, note) = row.map_err(StoreError::from_sqlite)?;
            let id = GoalId::from_str_unchecked(&id);
            match serde_json::from_str::<TargetKey>(&target_json) {
                Ok(target) => out.goals.push(Goal {
                    id,
                    target,
                    created_unix,
                    note,
                }),
                // Written by a version that knows about targets this one can't parse:
                // it stays in the file, gets named, and is left untouched.
                Err(_) => out.unreadable.push(id),
            }
        }
        Ok(out)
    }

    /// Inserts a new goal. An id that already exists is an error, not an update: ids
    /// are generated by the app (`GoalId::new`) and the caller never holds one worth
    /// overwriting — a collision is a bug, and overwriting the row would hide it by
    /// erasing the goal that was already there.
    ///
    /// `target_json` is the JSON of `ipc::TargetKey`, the on-disk format: see its own doc.
    pub fn add_goal(&self, g: &Goal) -> Result<(), StoreError> {
        // Serializing a `TargetKey` cannot fail (no maps, no floats): this branch
        // exists only so we're not calling `unwrap`, and if it ever did trigger it says why.
        let target_json = serde_json::to_string(&g.target).map_err(|e| StoreError::Unreadable {
            reason: e.to_string(),
        })?;
        self.conn
            .execute(
                "INSERT INTO goals (id, target_json, created_unix, note, seq)
                 VALUES (?1, ?2, ?3, ?4, COALESCE((SELECT max(seq) FROM goals), 0) + 1)",
                params![g.id.as_str(), target_json, g.created_unix, g.note],
            )
            .map(|_| ())
            .map_err(StoreError::from_sqlite)
    }

    /// `true` if it existed.
    pub fn remove_goal(&self, id: &GoalId) -> Result<bool, StoreError> {
        self.conn
            .execute("DELETE FROM goals WHERE id = ?1", params![id.as_str()])
            .map(|n| n > 0)
            .map_err(StoreError::from_sqlite)
    }

    /// The plan queue, as it was written.
    ///
    /// The nested `Result` is deliberate and mirrors `goals()`: the outer one is "the
    /// database failed", the inner one is "the document didn't parse". They are different
    /// situations — a broken file against a plan written by a version that knew more — and
    /// the screen says different things about them.
    pub fn queue(&self) -> Result<Result<plan::Queue, plan::QueueError>, StoreError> {
        let found: Option<String> = self
            .conn
            .query_row("SELECT rows_json FROM plan_queue WHERE id = 1", [], |r| {
                r.get(0)
            })
            .optional()
            .map_err(StoreError::from_sqlite)?;
        // No row yet is an empty queue, not a failure: a fresh database has no plan.
        Ok(match found {
            Some(json) => plan::Queue::from_json(&json),
            None => Ok(plan::Queue::default()),
        })
    }

    /// Replaces the document. The whole order is one value, so a write is one statement and
    /// there is no half-applied reorder to recover from.
    pub fn set_queue(&self, q: &plan::Queue) -> Result<(), StoreError> {
        self.write_queue_json(&q.to_json())
    }

    /// Writes a document straight in, for the test that an unreadable queue is declared
    /// rather than flattened to an empty one. There is no other way to reach that state
    /// through the public API, which is the point of the API.
    pub fn __corrupt_queue_for_tests(&self, raw: &str) -> Result<(), StoreError> {
        self.write_queue_json(raw)
    }

    fn write_queue_json(&self, raw: &str) -> Result<(), StoreError> {
        self.conn
            .execute(
                "INSERT INTO plan_queue (id, rows_json) VALUES (1, ?1)
                 ON CONFLICT(id) DO UPDATE SET rows_json = excluded.rows_json",
                params![raw],
            )
            .map(|_| ())
            .map_err(StoreError::from_sqlite)
    }
}
