//! The TypeScript contract, assembled from the types that cross the boundary.
//!
//! `ts-rs` renders a fieldless enum as a union of string literals. Frontend rule 5 forbids
//! literal unions — every component compares against a symbol (`MissingReason.SteamNotFound`)
//! — so each one is rewritten into the `const … as const` pair the repo already spells by
//! hand. **By form and not by a list of names**: rule 5 admits no exception, so there is no
//! union that should survive and nothing for a list to forget.

/// `steamNotFound` → `SteamNotFound`, `rep_plus` → `RepPlus`.
pub fn pascal_case(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    let mut upper = true;
    for c in value.chars() {
        if c == '_' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// The string literals of a union, or `None` if any member is something else.
fn string_members(body: &str) -> Option<Vec<&str>> {
    let mut members = Vec::new();
    for part in body.split('|') {
        let part = part.trim();
        let inner = part.strip_prefix('"')?.strip_suffix('"')?;
        if inner.contains('"') {
            return None;
        }
        members.push(inner);
    }
    (!members.is_empty()).then_some(members)
}

/// Rewrite every union of string literals in `file` into the `const … as const` pair.
pub fn to_const_enums(file: &str) -> String {
    let mut out = String::with_capacity(file.len());
    for (i, line) in file.lines().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        match rewrite_line(line) {
            Some(pair) => out.push_str(&pair),
            None => out.push_str(line),
        }
    }
    out
}

fn rewrite_line(line: &str) -> Option<String> {
    let rest = line.strip_prefix("export type ")?;
    let (name, body) = rest.split_once(" = ")?;
    let body = body.strip_suffix(';')?;
    let members = string_members(body)?;

    let mut pair = format!("export const {name} = {{\n");
    for m in &members {
        pair.push_str(&format!("  {}: \"{m}\",\n", pascal_case(m)));
    }
    pair.push_str("} as const;\n");
    pair.push_str(&format!(
        "export type {name} = (typeof {name})[keyof typeof {name}];"
    ));
    Some(pair)
}

use ts_rs::{Config, TS};

/// The header of the generated file. It names the command rather than describing the
/// situation: whoever opens this file is about to edit it by hand.
const HEADER: &str = "\
// Generated by `pnpm ipc:types` from the Rust types. Do not edit.
//
// The contract between Rust and Vue lives in the `#[serde]` attributes of `crates/ipc` and of
// the types that cross into it from `core-save`, `wiki` and `discovery`. `scripts/check` fails
// when this file and those types disagree.
";

/// One declaration: its JSDoc, then `export`, then the type itself.
fn decl<T: TS + ?Sized + 'static>(cfg: &Config, out: &mut String) {
    if let Some(docs) = <T as TS>::docs() {
        out.push_str(&docs);
    }
    out.push_str("export ");
    out.push_str(&<T as TS>::decl(cfg));
    out.push_str("\n\n");
}

/// The whole contract, in the order of the file.
///
/// The list **is** the registry of what crosses the boundary: a type that is not here does not
/// travel, and one that is reachable only as another's field cannot arrive by accident. An
/// incomplete list produces a file that does not compile, and `pnpm typecheck` is already in
/// `scripts/check`.
pub fn render() -> String {
    let cfg = Config::new().with_large_int("number");
    let mut out = String::with_capacity(32 * 1024);
    out.push_str(HEADER);
    out.push('\n');

    decl::<crate::ProfileId>(&cfg, &mut out);
    decl::<crate::CandidateSource>(&cfg, &mut out);
    decl::<discovery::SavePrefix>(&cfg, &mut out);
    decl::<crate::CandidateView>(&cfg, &mut out);
    decl::<crate::MissingReason>(&cfg, &mut out);
    decl::<crate::ChoiceReason>(&cfg, &mut out);
    decl::<crate::ActiveProfile>(&cfg, &mut out);
    decl::<crate::SteamView>(&cfg, &mut out);
    decl::<discovery::Edition>(&cfg, &mut out);
    decl::<discovery::Dlc>(&cfg, &mut out);
    decl::<crate::GameView>(&cfg, &mut out);
    decl::<crate::SetupState>(&cfg, &mut out);
    decl::<crate::SetupDiagnostic>(&cfg, &mut out);
    decl::<crate::Cell>(&cfg, &mut out);
    decl::<core_save::marks::CharacterGroup>(&cfg, &mut out);
    decl::<crate::CharacterRow>(&cfg, &mut out);
    decl::<crate::MarkArtView>(&cfg, &mut out);
    decl::<crate::MarksTotals>(&cfg, &mut out);
    decl::<crate::MarksMatrix>(&cfg, &mut out);
    decl::<core_save::Kind>(&cfg, &mut out);
    decl::<crate::SectionCount>(&cfg, &mut out);
    decl::<crate::SaveSummary>(&cfg, &mut out);
    decl::<crate::SaveDiagnostic>(&cfg, &mut out);
    decl::<crate::IoReason>(&cfg, &mut out);
    decl::<crate::SaveReason>(&cfg, &mut out);
    decl::<crate::SettingsReason>(&cfg, &mut out);
    decl::<crate::StoreReason>(&cfg, &mut out);
    decl::<crate::IpcError>(&cfg, &mut out);
    decl::<crate::ArchiveMode>(&cfg, &mut out);
    decl::<crate::ArchiveView>(&cfg, &mut out);
    decl::<crate::KindCounts>(&cfg, &mut out);
    decl::<crate::CatalogView>(&cfg, &mut out);
    decl::<crate::SpriteView>(&cfg, &mut out);
    decl::<crate::ExtractionReport>(&cfg, &mut out);
    decl::<crate::AchievementRef>(&cfg, &mut out);
    decl::<crate::MarkColumnView>(&cfg, &mut out);
    decl::<crate::MarkLevelView>(&cfg, &mut out);
    decl::<crate::ItemKindView>(&cfg, &mut out);
    decl::<crate::TargetKey>(&cfg, &mut out);
    decl::<crate::UnlockTarget>(&cfg, &mut out);
    decl::<crate::OriginView>(&cfg, &mut out);
    decl::<crate::GraphInfo>(&cfg, &mut out);
    decl::<crate::RequirementView>(&cfg, &mut out);
    decl::<crate::ThresholdItemView>(&cfg, &mut out);
    decl::<crate::UnlockNode>(&cfg, &mut out);
    decl::<crate::UnlockTotals>(&cfg, &mut out);
    decl::<crate::UnlockDiagnostic>(&cfg, &mut out);
    decl::<crate::UnlockView>(&cfg, &mut out);
    decl::<crate::StepsBasis>(&cfg, &mut out);
    decl::<crate::StepsSection>(&cfg, &mut out);
    decl::<crate::NextSteps>(&cfg, &mut out);
    decl::<crate::GraphViews>(&cfg, &mut out);
    decl::<crate::WantState>(&cfg, &mut out);
    decl::<crate::WantRoute>(&cfg, &mut out);
    decl::<crate::WantedView>(&cfg, &mut out);
    decl::<crate::WantDiagnostic>(&cfg, &mut out);
    decl::<crate::WantView>(&cfg, &mut out);
    decl::<crate::GoalId>(&cfg, &mut out);
    decl::<crate::GoalView>(&cfg, &mut out);
    decl::<crate::PlanStep>(&cfg, &mut out);
    decl::<crate::PlanExpansion>(&cfg, &mut out);
    decl::<crate::PlanDiagnostic>(&cfg, &mut out);
    decl::<crate::PlanView>(&cfg, &mut out);
    decl::<crate::SectionKind>(&cfg, &mut out);
    decl::<crate::Style>(&cfg, &mut out);
    decl::<crate::Dlc>(&cfg, &mut out);
    decl::<crate::Target>(&cfg, &mut out);
    decl::<crate::Inline>(&cfg, &mut out);
    decl::<crate::ListItem>(&cfg, &mut out);
    decl::<crate::Block>(&cfg, &mut out);
    decl::<wiki::CollectibleTemplate>(&cfg, &mut out);
    decl::<crate::Infobox>(&cfg, &mut out);
    decl::<crate::Section>(&cfg, &mut out);
    decl::<crate::Entry>(&cfg, &mut out);
    decl::<crate::WikiMissingReason>(&cfg, &mut out);
    decl::<crate::PatchView>(&cfg, &mut out);
    decl::<crate::WikiCounts>(&cfg, &mut out);
    decl::<crate::WikiInfo>(&cfg, &mut out);
    decl::<crate::WikiPageRef>(&cfg, &mut out);
    decl::<crate::WikiIndex>(&cfg, &mut out);
    decl::<crate::ProgressMark>(&cfg, &mut out);
    decl::<crate::SearchDiagnostic>(&cfg, &mut out);
    decl::<crate::SearchMatch>(&cfg, &mut out);
    decl::<crate::SearchHit>(&cfg, &mut out);
    decl::<crate::SearchView>(&cfg, &mut out);
    decl::<crate::QueueRow>(&cfg, &mut out);
    decl::<crate::QueueDiagnostic>(&cfg, &mut out);
    decl::<crate::QueueView>(&cfg, &mut out);
    decl::<crate::RunSource>(&cfg, &mut out);
    decl::<crate::RunOutcomeView>(&cfg, &mut out);
    decl::<crate::RunItemRef>(&cfg, &mut out);
    decl::<crate::RunView>(&cfg, &mut out);
    decl::<crate::RunTotals>(&cfg, &mut out);
    decl::<crate::RunsDiagnostic>(&cfg, &mut out);
    decl::<crate::RunsView>(&cfg, &mut out);
    decl::<crate::LiveOpen>(&cfg, &mut out);
    decl::<crate::LiveDiagnostic>(&cfg, &mut out);
    decl::<crate::LiveView>(&cfg, &mut out);
    decl::<crate::LockView>(&cfg, &mut out);
    decl::<crate::CollectionItem>(&cfg, &mut out);
    decl::<crate::CollectionTotals>(&cfg, &mut out);
    decl::<crate::CollectionDiagnostic>(&cfg, &mut out);
    decl::<crate::CollectionView>(&cfg, &mut out);
    decl::<crate::Settings>(&cfg, &mut out);

    to_const_enums(out.trim_end()) + "\n"
}
