//! The user's goals: what they want to unlock. The type lives here because it crosses
//! the IPC boundary; where it gets saved (`store`) is not the view-model's concern.

use catalog::{BossId, Catalog, ChallengeId, CharacterId, ItemId};
use serde::{Deserialize, Serialize};

use crate::catalog_view::{item_kind, ItemKindView};

/// Opaque id, generated by the app. Newtype: it's not a number, it's not a name, and
/// the frontend never constructs one.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct GoalId(String);

impl GoalId {
    /// A fresh id, 128 bits in hex built from the clock, the address of an allocation,
    /// and the pid. It guarantees exactly one thing: **it distinguishes goals created at
    /// different moments on the same machine**. It is not random (the clock dominates
    /// it) and it is not secret: don't use it as a token, and two different machines
    /// have no guarantee against generating the same id — that's fine, because
    /// databases never get merged.
    pub fn new() -> GoalId {
        use std::hash::{Hash, Hasher};
        let mut h = std::collections::hash_map::DefaultHasher::new();
        std::time::SystemTime::now().hash(&mut h);
        let probe = Box::new(0u8);
        (&*probe as *const u8 as usize).hash(&mut h);
        let a = h.finish();
        std::process::id().hash(&mut h);
        let b = h.finish();
        GoalId(format!("{a:016x}{b:016x}"))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Only for tests and for `store`, which reads back ids already generated.
    pub fn from_str_unchecked(s: &str) -> GoalId {
        GoalId(s.to_string())
    }
}

impl Default for GoalId {
    fn default() -> Self {
        GoalId::new()
    }
}

/// A target's identity, and it's `store`'s on-disk format: it only ever changes by
/// adding variants; a new field here invalidates the rows already saved. That's why it
/// carries no name or icon: those are live derivatives of the catalog, resolved on
/// every read via `graph::resolve_target`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(
    tag = "kind",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum TargetKey {
    Item { item_kind: ItemKindView, id: u32 },
    Character { id: u32 },
    Boss { id: u32 },
    Challenge { id: u32 },
}

impl TargetKey {
    /// The key in the form the UI shows, with the name (and icon) the catalog has
    /// resolved. Only one place builds an `UnlockTarget` from a key: it's the inverse
    /// of `UnlockTarget::key`, and the two are checked against each other.
    pub(crate) fn view(
        &self,
        name: String,
        icon_url: Option<String>,
        rewards: Vec<u32>,
    ) -> UnlockTarget {
        match *self {
            TargetKey::Item { item_kind: k, id } => UnlockTarget::Item {
                item_kind: k,
                id,
                name,
                icon_url,
            },
            TargetKey::Character { id } => UnlockTarget::Character { id, name },
            TargetKey::Boss { id } => UnlockTarget::Boss { id, name },
            TargetKey::Challenge { id } => UnlockTarget::Challenge { id, name, rewards },
        }
    }
}

/// What an achievement unlocks, or what a goal wants: the **view-model**, with name and
/// icon already resolved. It is never persisted — its `key` is what gets saved. The
/// field for the item's type is called `item_kind` because `kind` is the enum's tag:
/// calling it `kind` would produce JSON with two identical keys, and serde would accept
/// that silently.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "kind",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum UnlockTarget {
    Item {
        item_kind: ItemKindView,
        id: u32,
        name: String,
        icon_url: Option<String>,
    },
    Character {
        id: u32,
        name: String,
    },
    Boss {
        id: u32,
        name: String,
    },
    Challenge {
        id: u32,
        name: String,
        /// The achievements that completing it grants: ids, not views. The UI already
        /// has an achievement node in `UnlockView` (done or not, what it unlocks, icon)
        /// and looks it up by id; repeating those nodes here would make the type
        /// recursive. Empty when the file doesn't state the reward (challenges 31..=35
        /// and 45 as of 2026-09-05).
        rewards: Vec<u32>,
    },
}

impl UnlockTarget {
    /// This target's identity: what gets saved. Name and icon stay out, because the
    /// catalog can change them (or grow them) between one launch and the next.
    pub fn key(&self) -> TargetKey {
        match *self {
            UnlockTarget::Item {
                item_kind: k, id, ..
            } => TargetKey::Item { item_kind: k, id },
            UnlockTarget::Character { id, .. } => TargetKey::Character { id },
            UnlockTarget::Boss { id, .. } => TargetKey::Boss { id },
            UnlockTarget::Challenge { id, .. } => TargetKey::Challenge { id },
        }
    }
}

/// A goal as it lives in `store`: the key, not the view. What the UI receives is
/// `graph::GoalView`, which resolves the key against the current catalog.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Goal {
    pub id: GoalId,
    pub target: TargetKey,
    pub created_unix: i64,
    pub note: Option<String>,
}

/// Does the catalog know this key? A goal on a made-up id doesn't get saved.
pub fn target_exists(c: &Catalog, t: &TargetKey) -> bool {
    match *t {
        TargetKey::Item { item_kind: k, id } => c.item(item_kind(k), ItemId(id)).is_some(),
        TargetKey::Character { id } => c.character(CharacterId(id)).is_some(),
        TargetKey::Boss { id } => c.boss(BossId(id)).is_some(),
        TargetKey::Challenge { id } => c.challenge(ChallengeId(id)).is_some(),
    }
}
