//! The user's goals: what they want to unlock. The type lives here because it crosses
//! the IPC boundary; where it gets saved (`store`) is not the view-model's concern.

use catalog::{BossId, Catalog, ChallengeId, CharacterId, ItemId};
use serde::{Deserialize, Serialize};
use wiki::Target;

use crate::catalog_view::ItemKindView;

/// Opaque id, generated by the app. Newtype: it's not a number, it's not a name, and
/// the frontend never constructs one.
// No `#[serde(transparent)]`: a one-field tuple struct already serializes as its inner
// value, in both directions, and ts-rs's serde attribute parser, which knows four keys,
// prints `failed to parse serde attribute` for it on every build. The shape is pinned by
// `a_goal_id_is_a_bare_json_string_in_both_directions`. Not a doc comment: ts-rs copies
// those into `types.ts`, and this is about our build, not about the contract.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, ts_rs::TS)]
pub struct GoalId(String);

impl GoalId {
    /// An id, 128 bits in hex, hashed from what the caller hands in: the second the goal was
    /// created and a nonce `app` draws from the clock's nanoseconds, the pid and an
    /// allocation's address. `ipc` reads none of those itself, the way `roll`'s
    /// draw arrives with its seed — so the same inputs give the same id, and a test can say so.
    ///
    /// It guarantees exactly one thing: **different inputs give different ids** on this
    /// machine. It is not random and not secret: don't use it as a token, and two machines
    /// have no guarantee against the same id — fine, because databases never get merged.
    pub fn new(created_unix: i64, nonce: u64) -> GoalId {
        use std::hash::{Hash, Hasher};
        let mut h = std::collections::hash_map::DefaultHasher::new();
        created_unix.hash(&mut h);
        nonce.hash(&mut h);
        let a = h.finish();
        a.hash(&mut h);
        let b = h.finish();
        GoalId(format!("{a:016x}{b:016x}"))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Only for tests and for `store`, which reads back ids already generated.
    pub fn from_str_unchecked(s: &str) -> GoalId {
        GoalId(s.to_string())
    }
}

/// A target's identity, and it's `store`'s on-disk format: it only ever changes by
/// adding variants; a new field here invalidates the rows already saved. That's why it
/// carries no name or icon: those are live derivatives of the catalog, resolved on
/// every read via `graph::resolve_target`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, ts_rs::TS)]
#[serde(
    tag = "kind",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum TargetKey {
    Item { item_kind: ItemKindView, id: u32 },
    Character { id: u32 },
    Boss { id: u32 },
    Challenge { id: u32 },
}

/// Everything the catalog adds to a key to make it a view: what one variant needs the
/// others ignore. A struct rather than four parameters, so a new field is one line here
/// and not a fifth positional argument at every call.
#[derive(Debug, Default)]
pub(crate) struct Resolved {
    pub name: String,
    pub icon_url: Option<String>,
    pub rewards: Vec<u32>,
    pub tainted: bool,
    /// The dataset's page for this thing, when it has one. `None` is "nowhere to read about
    /// it": the name shows and does not link. The same rule `RequirementView` follows, and
    /// deliberately the same wording — one rule, two readers (`docs/BACKLOG.md` B35).
    pub page: Option<Target>,
}

impl TargetKey {
    /// The key in the form the UI shows, with the name (and icon) the catalog has
    /// resolved. Only one place builds an `UnlockTarget` from a key: it's the inverse
    /// of `UnlockTarget::key`, and the two are checked against each other.
    pub(crate) fn view(&self, r: Resolved) -> UnlockTarget {
        let Resolved {
            name,
            icon_url,
            rewards,
            tainted,
            page,
        } = r;
        match *self {
            TargetKey::Item { item_kind: k, id } => UnlockTarget::Item {
                item_kind: k,
                id,
                name,
                icon_url,
                page,
            },
            TargetKey::Character { id } => UnlockTarget::Character {
                id,
                name,
                tainted,
                page,
            },
            TargetKey::Boss { id } => UnlockTarget::Boss { id, name, page },
            TargetKey::Challenge { id } => UnlockTarget::Challenge {
                id,
                name,
                rewards,
                page,
            },
        }
    }
}

/// What an achievement unlocks, or what a goal wants: the **view-model**, with name and
/// icon already resolved. It is never persisted — its `key` is what gets saved. The
/// field for the item's type is called `item_kind` because `kind` is the enum's tag:
/// calling it `kind` would produce JSON with two identical keys, and serde would accept
/// that silently.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ts_rs::TS)]
#[serde(
    tag = "kind",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum UnlockTarget {
    Item {
        item_kind: ItemKindView,
        id: u32,
        name: String,
        icon_url: Option<String>,
        /// Where to read about it. `None` means the dataset has no page: the name shows and
        /// does not link, never a link that leads nowhere (B35). Same rule and same field as
        /// `RequirementView` — what a node unlocks and what blocks it are two halves of one
        /// row, and they answer alike.
        page: Option<Target>,
    },
    Character {
        id: u32,
        /// The game's name, English like every game name. The **base and Tainted forms share
        /// it**: `achievements.xml` writes *You unlocked "The Lost"* for both, so the name
        /// alone names two characters and the flag below is what tells them apart.
        name: String,
        /// The Tainted form, as `players.xml` declares it (the `b` in the portrait's name).
        /// The same pair the completion matrix identifies a character by.
        tainted: bool,
        page: Option<Target>,
    },
    Boss {
        id: u32,
        name: String,
        page: Option<Target>,
    },
    Challenge {
        id: u32,
        name: String,
        page: Option<Target>,
        /// The achievements that completing it grants: ids, not views. The UI already
        /// has an achievement node in `UnlockView` (done or not, what it unlocks, icon)
        /// and looks it up by id; repeating those nodes here would make the type
        /// recursive. Empty when the file doesn't state the reward (challenges 31..=35
        /// and 45 as of 2026-09-05).
        rewards: Vec<u32>,
    },
}

impl UnlockTarget {
    /// This target's identity: what gets saved. Name and icon stay out, because the
    /// catalog can change them (or grow them) between one launch and the next.
    pub fn key(&self) -> TargetKey {
        match *self {
            UnlockTarget::Item {
                item_kind: k, id, ..
            } => TargetKey::Item { item_kind: k, id },
            UnlockTarget::Character { id, .. } => TargetKey::Character { id },
            UnlockTarget::Boss { id, .. } => TargetKey::Boss { id },
            UnlockTarget::Challenge { id, .. } => TargetKey::Challenge { id },
        }
    }
}

/// A goal as it lives in `store`: the key, not the view. What the UI receives is
/// `graph::GoalView`, which resolves the key against the current catalog.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, ts_rs::TS)]
#[serde(rename_all = "camelCase")]
pub struct Goal {
    pub id: GoalId,
    pub target: TargetKey,
    pub created_unix: i64,
    pub note: Option<String>,
}

/// Does the catalog know this key? A goal on a made-up id doesn't get saved.
pub fn target_exists(c: &Catalog, t: &TargetKey) -> bool {
    match *t {
        TargetKey::Item { item_kind: k, id } => c.item(k, ItemId(id)).is_some(),
        TargetKey::Character { id } => c.character(CharacterId(id)).is_some(),
        TargetKey::Boss { id } => c.boss(BossId(id)).is_some(),
        TargetKey::Challenge { id } => c.challenge(ChallengeId(id)).is_some(),
    }
}
