export const Command = {
  SetupState: 'setup_state',
  SelectProfile: 'select_profile',
  SaveSummary: 'save_summary',
  Completion: 'completion',
  ExtractionReport: 'extraction_report',
  Unlock: 'unlock',
  NextSteps: 'next_steps',
  Collection: 'collection',
  Plan: 'plan',
  AddGoal: 'add_goal',
  RemoveGoal: 'remove_goal',
  WikiEntry: 'wiki_entry',
  Queue: 'queue',
  QueueAdd: 'queue_add',
  QueueRemove: 'queue_remove',
  QueueMove: 'queue_move',
  QueueImportGoals: 'queue_import_goals',
} as const
