export const Command = {
  SetupState: 'setup_state',
  Settings: 'settings',
  SetScale: 'set_scale',
  SetStayInBackground: 'set_stay_in_background',
  SetResumeTabs: 'set_resume_tabs',
  WindowSession: 'window_session',
  SetWindowSession: 'set_window_session',
  SelectProfile: 'select_profile',
  SaveSummary: 'save_summary',
  Completion: 'completion',
  ExtractionReport: 'extraction_report',
  GraphViews: 'graph_views',
  Want: 'want',
  Collection: 'collection',
  Plan: 'plan',
  AddGoal: 'add_goal',
  RemoveGoal: 'remove_goal',
  WikiEntry: 'wiki_entry',
  WikiIndex: 'wiki_index',
  Search: 'search',
  Queue: 'queue',
  QueueAdd: 'queue_add',
  QueueRemove: 'queue_remove',
  QueueMove: 'queue_move',
  QueueImportGoals: 'queue_import_goals',
  Runs: 'runs',
} as const
