use ipc::{Goal, GoalId, ItemKindView, TargetKey};
use store::{Store, StoreError, SCHEMA_VERSION};

fn goal(id: &str, item_id: u32) -> Goal {
    Goal {
        id: GoalId::from_str_unchecked(id),
        target: TargetKey::Item {
            item_kind: ItemKindView::Passive,
            id: item_id,
        },
        created_unix: 1_700_000_000,
        note: None,
    }
}

fn item_ids(read: &[Goal]) -> Vec<u32> {
    read.iter()
        .map(|g| match g.target {
            TargetKey::Item { id, .. }
            | TargetKey::Character { id }
            | TargetKey::Boss { id }
            | TargetKey::Challenge { id } => id,
        })
        .collect()
}

#[test]
fn open_creates_the_schema_at_the_current_version() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("isaacdome.db");
    let s = Store::open(&path).unwrap();
    assert_eq!(s.schema_version().unwrap(), SCHEMA_VERSION);
    assert!(s.goals().unwrap().goals.is_empty());
}

#[test]
fn goals_survive_reopening_and_the_migration_does_not_rerun() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("isaacdome.db");
    {
        let s = Store::open(&path).unwrap();
        s.add_goal(&goal("a", 1)).unwrap();
        s.add_goal(&goal("b", 2)).unwrap();
    }
    let s = Store::open(&path).unwrap();
    assert_eq!(
        item_ids(&s.goals().unwrap().goals),
        vec![1, 2],
        "in insertion order"
    );
    assert_eq!(s.schema_version().unwrap(), SCHEMA_VERSION);
}

/// The saved row carries the key and nothing else: name and icon are derived from the
/// catalog, and a base64 data URL in a text column would turn this into an image
/// database. If this test breaks, the on-disk format has changed.
#[test]
fn the_saved_row_carries_only_the_key() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("x.db");
    Store::open(&path).unwrap().add_goal(&goal("a", 7)).unwrap();
    let conn = rusqlite::Connection::open(&path).unwrap();
    let json: String = conn
        .query_row("SELECT target_json FROM goals WHERE id = 'a'", [], |r| {
            r.get(0)
        })
        .unwrap();
    assert_eq!(json, r#"{"kind":"item","itemKind":"passive","id":7}"#);
    assert!(!json.contains("name"), "{json}");
    assert!(!json.contains("iconUrl"), "{json}");
}

#[test]
fn remove_goal_reports_whether_it_existed() {
    let dir = tempfile::tempdir().unwrap();
    let s = Store::open(&dir.path().join("x.db")).unwrap();
    s.add_goal(&goal("a", 1)).unwrap();
    assert!(s.remove_goal(&GoalId::from_str_unchecked("a")).unwrap());
    assert!(!s.remove_goal(&GoalId::from_str_unchecked("a")).unwrap());
    assert!(s.goals().unwrap().goals.is_empty());
}

/// Ids are generated by the app and never repeat: a collision is a bug, and an `INSERT`
/// that overwrote the row would hide it by erasing the goal that was already there.
#[test]
fn adding_the_same_id_twice_fails_and_the_first_row_survives() {
    let dir = tempfile::tempdir().unwrap();
    let s = Store::open(&dir.path().join("x.db")).unwrap();
    s.add_goal(&goal("a", 1)).unwrap();
    assert!(
        matches!(
            s.add_goal(&goal("a", 2)),
            Err(StoreError::Unreadable { .. })
        ),
        "the primary key constraint is a SQLite error, and it doesn't cross the IPC boundary"
    );
    assert_eq!(
        item_ids(&s.goals().unwrap().goals),
        vec![1],
        "the earlier row is intact"
    );
}

#[test]
fn a_newer_schema_is_refused_not_destroyed() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("x.db");
    {
        let conn = rusqlite::Connection::open(&path).unwrap();
        conn.pragma_update(None, "user_version", SCHEMA_VERSION + 5)
            .unwrap();
        conn.execute_batch("CREATE TABLE future (x INTEGER);")
            .unwrap();
    }
    match Store::open(&path) {
        Err(StoreError::NewerSchema { found, supported }) => {
            assert_eq!((found, supported), (SCHEMA_VERSION + 5, SCHEMA_VERSION));
        }
        other => panic!("expected NewerSchema, got {other:?}"),
    }
    // The file is intact: the future table is still there.
    let conn = rusqlite::Connection::open(&path).unwrap();
    let n: i64 = conn
        .query_row(
            "SELECT count(*) FROM sqlite_master WHERE name='future'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(n, 1);
}

#[test]
fn a_file_that_is_not_sqlite_is_unreadable_not_a_panic() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("x.db");
    std::fs::write(&path, b"questo non e' un database").unwrap();
    assert!(matches!(
        Store::open(&path),
        Err(StoreError::Unreadable { .. })
    ));
}

#[test]
fn a_row_with_broken_json_is_reported_by_id_and_the_others_are_read() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("x.db");
    {
        let s = Store::open(&path).unwrap();
        s.add_goal(&goal("a", 1)).unwrap();
    }
    // A row written by someone else (or by a future version) with a target this version
    // can't parse: inserted by hand. `c` comes after, so `b` really does sit in the
    // middle (seq 1 < 15 < 16), and a read that stopped at the first unreadable row
    // would lose `c`.
    {
        let conn = rusqlite::Connection::open(&path).unwrap();
        conn.execute(
            "INSERT INTO goals (id, target_json, created_unix, note, seq) VALUES ('b', '{\"kind\":\"planet\"}', 0, NULL, 15)",
            [],
        )
        .unwrap();
    }
    Store::open(&path).unwrap().add_goal(&goal("c", 3)).unwrap();
    let read = Store::open(&path).unwrap().goals().unwrap();
    assert_eq!(
        read.goals.iter().map(|g| g.id.as_str()).collect::<Vec<_>>(),
        vec!["a", "c"],
        "the good rows all read back, in the usual order"
    );
    assert_eq!(read.unreadable, vec![GoalId::from_str_unchecked("b")]);
}
