// Generated by `pnpm ipc:types` from the Rust types. Do not edit.
//
// The contract between Rust and Vue lives in the `#[serde]` attributes of `crates/ipc` and of
// the types that cross into it from `core-save`, `wiki` and `discovery`. `scripts/check` fails
// when this file and those types disagree.

/**
 * Opaque matching key between a persisted choice and a candidate.
 * Newtype to prevent a path from ending up in here by mistake.
 */
export type ProfileId = string

/**
 * The save's origin, without the data that `discovery`'s type carries along with it
 * (Steam account id, folder): those don't cross the IPC boundary. A fieldless enum:
 * on the wire it's a bare camelCase string (`"steamCloud"`), not a tagged object.
 */
export const CandidateSource = {
  SteamCloud: 'steamCloud',
  Documents: 'documents',
  Manual: 'manual',
} as const
export type CandidateSource =
  (typeof CandidateSource)[keyof typeof CandidateSource]

/**
 * The two save-file name prefixes, `rep_` and `rep+`. A domain enum: it keeps its own
 * `snake_case` on the wire, unlike the ones the boundary defines for itself.
 */
export const SavePrefix = {
  Rep: 'rep',
  RepPlus: 'rep_plus',
} as const
export type SavePrefix = (typeof SavePrefix)[keyof typeof SavePrefix]

/**
 * A count the file may not let us make. **Never `Read { done: 0 }` for a section that was
 * not read**: a zero is a profile at the start, and the two are not one sentence. Same
 * choice as `Verdict::Partial` in `graph` and `Generated::NotSaid` in `run`.
 */
export type PreviewCount =
  { kind: 'read'; done: number; of: number } | { kind: 'unread' }

export type CandidatePreview = {
  achievements: PreviewCount
  items: PreviewCount
  /**
   * Cells that reached a level, out of the cells the file lets us read — the denominator
   * Completion already uses, where what cannot be read stays outside it.
   */
  marks: PreviewCount
  /**
   * Cells the file does not let us read. Zero when the matrix is whole, and zero as well
   * when there is no counters section at all: that absence is `marks: Unread`, not 408
   * unreadable cells.
   */
  unreadableCells: number
}

export type CandidateView = {
  id: ProfileId
  prefix: SavePrefix
  slot: number
  source: CandidateSource
  modifiedUnix: number | null
  sizeBytes: number
  suggested: boolean
  /**
   * Display-only detail. No command accepts it as input.
   */
  pathHint: string
  /**
   * What the file says about itself, for the welcome's cards. `None` when it could not be
   * opened or parsed **at all**: the row is still offered — "degrade, never fail" shows it
   * and says so, it does not decide a stranger has no save.
   *
   * Filled by [`setup_state`], never by [`candidates`]: that list is the one
   * `select_profile` validates against, and it reads no files.
   */
  preview: CandidatePreview | null
}

/**
 * Where the chain from Steam to the game to the saves broke down. A fieldless enum: on the wire it's
 * a bare camelCase string, `"steamNotFound"` and neither `"SteamNotFound"` nor
 * `{"kind":"steamNotFound"}`. The convention holds for **every** enum on the IPC —
 * `rename_all = "camelCase"` always, the tag only where variants carry data: if two
 * enums followed different conventions, a `switch` on the TypeScript side would fall
 * into no branch at all, and nothing would flag it.
 */
export const MissingReason = {
  SteamNotFound: 'steamNotFound',
  GameNotFound: 'gameNotFound',
  NoSaves: 'noSaves',
  NoSavesInChosenFolder: 'noSavesInChosenFolder',
} as const
export type MissingReason = (typeof MissingReason)[keyof typeof MissingReason]

export type ChoiceReason =
  { kind: 'neverChosen' } | { kind: 'savedProfileGone'; was: string }

export type ActiveProfile =
  | { kind: 'none'; reason: MissingReason }
  | { kind: 'needsChoice'; reason: ChoiceReason; suggested: ProfileId | null }
  | { kind: 'active'; profile: CandidateView; autoSelected: boolean }

export type SteamView = {
  /**
   * Display-only path: tells the user where it was found.
   */
  rootHint: string
  libraries: number
}

export const Edition = {
  Rebirth: 'rebirth',
  Afterbirth: 'afterbirth',
  AfterbirthPlus: 'afterbirth_plus',
  Repentance: 'repentance',
  RepentancePlus: 'repentance_plus',
} as const
export type Edition = (typeof Edition)[keyof typeof Edition]

export const InstalledDlc = {
  Afterbirth: 'afterbirth',
  AfterbirthPlus: 'afterbirth_plus',
  Repentance: 'repentance',
  RepentancePlus: 'repentance_plus',
} as const
export type InstalledDlc = (typeof InstalledDlc)[keyof typeof InstalledDlc]

export type GameView = {
  dirHint: string
  edition: Edition
  dlcs: Array<InstalledDlc>
}

export type SetupState = {
  steam: SteamView | null
  game: GameView | null
  candidates: Array<CandidateView>
  active: ActiveProfile
  diagnostics: Array<SetupDiagnostic>
}

/**
 * What failed during discovery. Carries **only the last path component**:
 * the full path contains the Steam account id under `userdata/`
 * and always the Windows username.
 */
export type SetupDiagnostic =
  | { kind: 'steamNotFound' }
  | { kind: 'gameNotFound' }
  | { kind: 'noSavesFound' }
  | { kind: 'noSavesInChosenFolder' }
  | { kind: 'unreadablePath'; name: string; reason: IoReason }
  | { kind: 'malformedManifest'; name: string }

/**
 * A cell of the matrix. The three variants are the module's reason for existing:
 * "never done", "not readable", and "suspicious value" are three different things.
 */
export type Cell =
  | { kind: 'known'; bits: number }
  | { kind: 'unknown' }
  | { kind: 'unexpected'; value: number }

/**
 * Which block family a row belongs to. It is the file's structure, not the player's way
 * of grouping characters: the three families are where the unread cells live.
 */
export const CharacterGroup = {
  Original: 'original',
  Forgotten: 'forgotten',
  Later: 'later',
} as const
export type CharacterGroup =
  (typeof CharacterGroup)[keyof typeof CharacterGroup]

/**
 * `tainted` groups the rows the way a player does, while `group` stays the three blocks the
 * file itself has. Every URL is `None` when the game archives are not open, and the screen
 * draws the fallback outfit.
 */
export type CharacterRow = {
  character: string
  group: CharacterGroup
  /**
   * The Tainted form. The screen groups rows the way a player does, base and Tainted,
   * while `group` stays the file's three blocks — which is where the unread cells live.
   */
  tainted: boolean
  cells: Array<Cell>
  /**
   * The co-op menu head. `None` without a catalog, or for a character the menu doesn't
   * draw.
   */
  headUrl: string | null
}

/**
 * The symbol URLs of one column, one per tier. Both `None` when the game's archives
 * aren't open: the screen draws the fallback outfit instead.
 */
export type MarkArtView = { normalUrl: string | null; hardUrl: string | null }

export type MarksTotals = {
  cells: number
  readable: number
  unknown: number
  unexpected: number
  /**
   * Cells that reached *a* level — bit 0 or bit 1. A mark taken on hard counts as taken
   * on normal too (B22), so this is the larger of the two and `hard` is a subset of it,
   * never a tally beside it.
   */
  normal: number
  /**
   * Cells that reached the second level — bit 1. `hard <= normal <= readable` always.
   */
  hard: number
}

export type MarksMatrix = {
  characters: Array<CharacterRow>
  bosses: Array<string>
  /**
   * `art[i]` draws `bosses[i]`: a parallel array, so `bosses` keeps the shape the design
   * was built on.
   */
  art: Array<MarkArtView>
  totals: MarksTotals
}

/**
 * The ten sections of the save.
 *
 * A name here is either **structural** — the position in the file, nothing claimed about
 * the content — or **earned by a measurement of its own**. The `Unknown*` variants are
 * the first kind and say so. `LevelCounters` and `Bosses` are the second: they used to
 * read `PerChar` and `CardsPills`, labels that came from watching bits flip, and both
 * were wrong. See `docs/BACKLOG.md`, B9.
 *
 * The game's own names, printed as `Reading chunk N` when it loads a profile, are strong
 * evidence but not a measurement — a log line says what the game thinks it is reading.
 * Sections 5 and 9 have such a name (Mini Bosses, GameSettings) and stay `Unknown` here
 * until one of them is checked against the bytes, which is the whole point of the
 * distinction.
 *
 * **Section 8 earned its name on 2026-09-15** and stopped being `Unknown8`. A matched
 * window around one solo run: the log plays `playing cutscene 22 (The Void)` exactly once
 * and cell **22** of this section rises by exactly one, which is the second point on the
 * identity mapping after 19. The game's `Reading chunk 8 / Cutscene Counters` agrees, and
 * now it is agreeing with something rather than standing alone.
 *
 * **What the name does not settle**: cell **2** also rose by one in that window, no
 * cutscene 2 was played in the log that survives, and cell 1 did **not** move although the
 * Intro (cutscene 1) did play. So the identity holds where it was checked and this section
 * is not simply "cutscene N at index N" — see `docs/BACKLOG.md`, B9.
 */
export const Kind = {
  Achievements: 'achievements',
  Counters: 'counters',
  LevelCounters: 'level_counters',
  Items: 'items',
  Unknown5: 'unknown5',
  Bosses: 'bosses',
  Challenges: 'challenges',
  CutsceneCounters: 'cutscene_counters',
  Unknown9: 'unknown9',
  Bestiary: 'bestiary',
} as const
export type Kind = (typeof Kind)[keyof typeof Kind]

/**
 * Count for one section. Carries the `Kind`, not a translated label:
 * the human-readable name is a UI string and lives in the i18n files.
 */
export type SectionCount = { kind: Kind; count: number }

export type SaveSummary = {
  profile: ProfileId
  sections: Array<SectionCount>
  diagnostics: Array<SaveDiagnostic>
}

/**
 * What could not be read from the save. Carries no offsets or lengths:
 * the frontend has no knowledge of the file layout.
 */
export type SaveDiagnostic =
  | { kind: 'unexpectedKind'; expected: number; found: number }
  | { kind: 'sectionOverrun'; section: number }
  | { kind: 'trailingBytes' }

/**
 * What the operating system said, reduced to the two cases a user can act on. Anything
 * else is `Other`: a third guess at what the OS meant would be wording, not information.
 *
 * No variant carries a field, so this is a bare camelCase string on the wire and the
 * TypeScript mirrors it as a union of values.
 */
export const IoReason = {
  NotFound: 'notFound',
  PermissionDenied: 'permissionDenied',
  Other: 'other',
} as const
export type IoReason = (typeof IoReason)[keyof typeof IoReason]

/**
 * Why the active profile's save could not be read.
 */
export type SaveReason =
  { kind: 'tooShort' } | { kind: 'badMagic' } | { kind: 'io'; reason: IoReason }

/**
 * Why `settings.json` could not be written. The only state the app persists outside its
 * own database, and the one file whose loss the user notices immediately.
 */
export type SettingsReason =
  | { kind: 'configDirUnknown' }
  | { kind: 'io'; reason: IoReason }
  | { kind: 'encoding' }

/**
 * Why the app's database is unavailable. `NewerSchema` is the only one the user can act
 * on, which is why its two versions travel as numbers instead of inside a sentence.
 */
export type StoreReason =
  | { kind: 'dataDirUnknown' }
  | { kind: 'dataDirNotCreatable' }
  | { kind: 'unreadable' }
  | { kind: 'newerSchema'; found: number; supported: number }
  | { kind: 'queueUnparseable' }

/**
 * Error that crosses the IPC boundary. Tagged, not a string: the UI must be able to
 * tell "no active profile" apart from "unreadable file" without parsing text.
 */
export type IpcError =
  | { kind: 'noActiveProfile' }
  | { kind: 'unknownProfile'; id: string }
  | { kind: 'unreadableSave'; reason: SaveReason }
  | { kind: 'settingsNotWritable'; reason: SettingsReason }
  | { kind: 'unknownTarget' }
  | { kind: 'catalogUnavailable' }
  | { kind: 'storeUnavailable'; reason: StoreReason }
  | { kind: 'wikiUnavailable' }
  | { kind: 'sessionTooLarge' }
  | { kind: 'autostartNotWritable'; reason: AutostartFailure }

/**
 * The compression mode, remapped onto an enum **of our own**.
 *
 * `unpack::CompressionMode` has a newtype variant (`Unknown(u8)`), a shape the project's
 * rules forbid past the IPC boundary. Here it becomes a tagged struct variant.
 */
export type ArchiveMode =
  | { kind: 'bogocrypt1' }
  | { kind: 'lzw' }
  | { kind: 'miniZ' }
  | { kind: 'bogocrypt2' }
  | { kind: 'unknown'; value: number }

/**
 * An archive as the UI sees it.
 */
export type ArchiveView = { name: string; mode: ArchiveMode; entries: number }

export type KindCounts = {
  passives: number
  actives: number
  familiars: number
  trinkets: number
}

export type CatalogView = {
  counts: KindCounts
  total: number
  /**
   * How many distinct keys (names, descriptions, character names) the stringtable
   * doesn't know: the catalog's `Diagnostic::UnresolvedKey`, counted one per key.
   */
  unresolvedNames: number
  languages: Array<string>
}

/**
 * An icon already resolved: the frontend sees neither paths nor raw bytes.
 */
export type SpriteView = { id: number; name: string; dataUrl: string }

/**
 * Everything the verification screen shows about the extraction.
 */
export type ExtractionReport = {
  archives: Array<ArchiveView>
  /**
   * Total entries across the indexes of the opened archives.
   */
  totalEntries: number
  /**
   * `None` when the catalog couldn't be read: game absent, or `items.xml` unreadable.
   */
  catalog: CatalogView | null
  sprites: Array<SpriteView>
  /**
   * The state of the wiki dataset: independent of the archives, loaded or not
   * regardless of how the extraction went.
   */
  wiki: WikiInfo
}

/**
 * One rule for the enums on this boundary: those whose variants carry different data are
 * tagged on `kind`; those with no fields travel as a bare string. `UnlockTarget::Item`
 * carries `item_kind`, not `kind`, because `kind` is the tag.
 */
export type AchievementRef =
  | {
      kind: 'known'
      id: number
      text: string
      /**
       * **How to get it**, in one line: the game's own `unlock_condition` when
       * `achievements.xml` states one, and the wiki's requirement when it does not.
       *
       * Two sources, because the file alone is not enough. Measured 2026-09-13 on the
       * reference profile: of 637 known achievements the file answers for 283, and among
       * the 119 unlockable *now* — what the landing page draws from — for only 16. It was
       * called `hint` while it was only the file's; the name changed with the meaning, so
       * that every reader had to be revisited rather than silently widened.
       *
       * The game's words win where it has any: the wiki is the fallback, never a rewrite.
       */
      condition: string | null
      iconUrl: string | null
    }
  | { kind: 'unknown'; slot: number }

/**
 * The twelve columns, as a value on the wire. Fieldless, so it is a bare camelCase string
 * and the TypeScript is a union of values — the repo's rule, zero exceptions.
 */
export const MarkColumnView = {
  MomsHeart: 'momsHeart',
  Isaac: 'isaac',
  Satan: 'satan',
  BossRush: 'bossRush',
  BlueBaby: 'blueBaby',
  TheLamb: 'theLamb',
  MegaSatan: 'megaSatan',
  Greed: 'greed',
  Hush: 'hush',
  Delirium: 'delirium',
  Mother: 'mother',
  TheBeast: 'theBeast',
} as const
export type MarkColumnView =
  (typeof MarkColumnView)[keyof typeof MarkColumnView]

/**
 * A level inside a cell, named for its bit. `Second` is Ultra Greedier in the Greed
 * column, measured; what it means elsewhere is not, and `hard` would ship that claim.
 */
export const MarkLevelView = {
  Base: 'base',
  Second: 'second',
} as const
export type MarkLevelView = (typeof MarkLevelView)[keyof typeof MarkLevelView]

/**
 * A fieldless enum: on the wire it's a bare camelCase string (`"passive"`), like
 * `OriginView`. The tag exists to distinguish variants that carry different data, and
 * here there are none: `{"kind":"passive"}` would cost a key on every row and say
 * nothing more. The day a variant gains a field, the enum becomes tagged and the
 * TypeScript side follows.
 */
export const ItemKindView = {
  Passive: 'passive',
  Active: 'active',
  Familiar: 'familiar',
  Trinket: 'trinket',
} as const
export type ItemKindView = (typeof ItemKindView)[keyof typeof ItemKindView]

/**
 * A target's identity, and it's `store`'s on-disk format: it only ever changes by
 * adding variants; a new field here invalidates the rows already saved. That's why it
 * carries no name or icon: those are live derivatives of the catalog, resolved on
 * every read via `graph::resolve_target`.
 */
export type TargetKey =
  | { kind: 'item'; itemKind: ItemKindView; id: number }
  | { kind: 'character'; id: number }
  | { kind: 'boss'; id: number }
  | { kind: 'challenge'; id: number }

/**
 * What an achievement unlocks, or what a goal wants: the **view-model**, with name and
 * icon already resolved. It is never persisted — its `key` is what gets saved. The
 * field for the item's type is called `item_kind` because `kind` is the enum's tag:
 * calling it `kind` would produce JSON with two identical keys, and serde would accept
 * that silently.
 */
export type UnlockTarget =
  | {
      kind: 'item'
      itemKind: ItemKindView
      id: number
      name: string
      iconUrl: string | null
      /**
       * Where to read about it. `None` means the dataset has no page: the name shows and
       * does not link, never a link that leads nowhere (B35). Same rule and same field as
       * `RequirementView` — what a node unlocks and what blocks it are two halves of one
       * row, and they answer alike.
       */
      page: Target | null
    }
  | {
      kind: 'character'
      id: number
      /**
       * The game's name, English like every game name. The **base and Tainted forms share
       * it**: `achievements.xml` writes *You unlocked "The Lost"* for both, so the name
       * alone names two characters and the flag below is what tells them apart.
       */
      name: string
      /**
       * The Tainted form, as `players.xml` declares it (the `b` in the portrait's name).
       * The same pair the completion matrix identifies a character by.
       */
      tainted: boolean
      page: Target | null
    }
  | { kind: 'boss'; id: number; name: string; page: Target | null }
  | {
      kind: 'challenge'
      id: number
      name: string
      page: Target | null
      /**
       * The achievements that completing it grants: ids, not views. The UI already
       * has an achievement node in `UnlockView` (done or not, what it unlocks, icon)
       * and looks it up by id; repeating those nodes here would make the type
       * recursive. Empty when the file doesn't state the reward (challenges 31..=35
       * and 45 as of 2026-09-05).
       */
      rewards: Array<number>
    }

/**
 * `catalog::Origin` doesn't cross the IPC boundary: this is its view, like `ItemKindView` for `ItemKind`.
 */
export const OriginView = {
  Rebirth: 'rebirth',
  Afterbirth: 'afterbirth',
  AfterbirthPlus: 'afterbirthPlus',
  Repentance: 'repentance',
} as const
export type OriginView = (typeof OriginView)[keyof typeof OriginView]

/**
 * `Partial` carries no count of the steps still missing, on purpose: with a requirement
 * uninterpreted, or a node caught in a cycle, the transitive count is not knowable, and a zero
 * would read as "nothing in the way". A node that is `Partial` must never be drawn as
 * unlockable.
 */
export type GraphInfo =
  | {
      kind: 'computed'
      availableNow: boolean
      blockedBy: number
      fanOut: number
      stepsMissing: number
    }
  | { kind: 'partial'; blockedBy: number; fanOut: number; unknown: number }

/**
 * What a node is still missing. Typed because the type decides both the grouping and
 * whether there is an achievement behind it at all.
 */
export type RequirementView =
  | {
      kind: 'character'
      id: number
      /**
       * Shared by the base and Tainted forms, like `UnlockTarget::Character`: the flag
       * beside it is what tells the two apart.
       */
      name: string
      tainted: boolean
      /**
       * The wiki page that says how *this* is unlocked. `None` means the dataset has no
       * page for it: the name shows and does not link. Never "no requirement".
       */
      page: Target | null
    }
  | { kind: 'boss'; id: number; name: string; page: Target | null }
  | { kind: 'challenge'; id: number; name: string; page: Target | null }
  | {
      kind: 'item'
      itemKind: ItemKindView
      id: number
      name: string
      page: Target | null
    }
  | { kind: 'gate'; label: string }
  | {
      kind: 'mark'
      character: number
      characterName: string
      column: MarkColumnView
      level: MarkLevelView
    }
  | { kind: 'counter'; label: string; current: number; atLeast: number }
  | {
      kind: 'threshold'
      transformation: number
      label: string
      current: number
      atLeast: number
      of: Array<ThresholdItemView>
      /**
       * How many of the wiki's contributors this catalog does not have. They can only
       * ever add to `current`, never subtract, so a non-zero value means the count shown
       * is a floor.
       */
      unresolved: number
      /**
       * The transformation's own wiki page.
       */
      page: Target | null
    }
  | { kind: 'unknown'; label: string }

/**
 * One item of a threshold's set, with where the profile stands on it.
 */
export type ThresholdItemView = {
  /**
   * `itemKind` and not `kind`, for the same reason as `RequirementView::Item`.
   */
  itemKind: ItemKindView
  id: number
  name: string
  /**
   * Whether the profile can already find it: its achievement is done, or nothing gates it.
   */
  unlocked: boolean
  page: Target | null
}

export type UnlockNode = {
  achievement: AchievementRef
  /**
   * From the save, section 1: real.
   */
  done: boolean
  /**
   * From the catalog, reverse index: real. Empty if it unlocks nothing known.
   */
  unlocks: Array<UnlockTarget>
  /**
   * Origin DLC of the first item unlocked: real.
   */
  origin: OriginView | null
  /**
   * What is still in the way, typed by the nature of the target. This is what the
   * screen groups by: "you're missing 1 character and 2 bosses" instead of
   * "blocked by 3".
   */
  missing: Array<RequirementView>
  /**
   * What the graph knows.
   */
  graph: GraphInfo
}

export type UnlockTotals = {
  slots: number
  done: number
  known: number
  unknown: number
}

/**
 * `NoAchievementSection` means section 1 of the save was not read: nodes and totals are
 * zero, and that does not mean "zero achievements done".
 */
export type UnlockDiagnostic =
  | { kind: 'slotsBeyondCatalog'; count: number }
  | { kind: 'catalogBeyondSlots'; count: number }
  | { kind: 'noCatalog' }
  | { kind: 'noAchievementSection' }

export type UnlockView = {
  nodes: Array<UnlockNode>
  totals: UnlockTotals
  diagnostics: Array<UnlockDiagnostic>
}

/**
 * What a section is ordered by. A fieldless enum: on the wire it's `"fanOut"`, not a
 * tagged object — the same rule as `ItemKindView` and `OriginView`.
 *
 * `Closeness` is the basis this type was left open for. A counter is the **only**
 * requirement that carries a distance — a mark is binary and a character is a wall — so it
 * is the only one that can order a list by how near the profile is.
 */
export const StepsBasis = {
  FanOut: 'fanOut',
  Closeness: 'closeness',
} as const
export type StepsBasis = (typeof StepsBasis)[keyof typeof StepsBasis]

/**
 * One reason, and the steps it produced. The screen draws the basis as a heading, because a
 * row is worth showing only together with why it is being suggested.
 */
export type StepsSection = { basis: StepsBasis; steps: Array<UnlockNode> }

export type NextSteps = { sections: Array<StepsSection> }

/**
 * Both answers the graph's screens need, from one reading of the profile (N8).
 *
 * They were two commands, and the frontend asked for them together — with a comment saying
 * why: *"one read, because both answers belong to the same profile and asking twice could
 * straddle a change"*. Two commands could not keep that promise. Each rebuilt the whole
 * pipeline behind it: the settings file, a walk of the Steam libraries, the `.dat` read
 * whole, its parse, 642 nodes and the evaluation — **twice for one screen load**, and
 * across two moments, so a save written in between made the steps disagree with the list
 * they are a filter over.
 *
 * One command is not a cache: there is nothing to invalidate, and nothing is remembered
 * between calls. The steps stay a pure function of the view here, as they always were.
 */
export type GraphViews = { unlock: UnlockView; steps: NextSteps }

/**
 * B37 — a want read from the other end of the graph: you name a thing, and these are the
 * ways to it. `routes` is a list because a challenge can be named by two achievements (14 of
 * 45 are, measured 2026-09-13); an empty list always travels with the diagnostic that says
 * which empty it is.
 */
export type WantState =
  | { kind: 'done' }
  | { kind: 'availableNow' }
  | { kind: 'chain'; steps: Array<UnlockNode>; unknown: number }
  | { kind: 'noProfile' }

export type WantRoute = { node: UnlockNode; state: WantState }

/**
 * A want is one of two things, and `UnlockTarget` can only be one of them: it has four
 * variants and none is an achievement. Naming *Greedier!* has to reach the node whose
 * target the catalog does not model, so the view carries both — and a third case for a name
 * the catalog no longer resolves.
 */
export type WantedView =
  | { kind: 'target'; target: UnlockTarget }
  | { kind: 'achievement'; achievement: AchievementRef }
  | { kind: 'unresolved' }

export type WantDiagnostic =
  | { kind: 'noCatalog' }
  | { kind: 'noProfile' }
  | { kind: 'nothingUnlocks' }
  | { kind: 'notUnlockable' }

export type WantView = {
  wanted: WantedView
  routes: Array<WantRoute>
  diagnostics: Array<WantDiagnostic>
}

/**
 * Opaque id, generated by the app. Newtype: it's not a number, it's not a name, and
 * the frontend never constructs one.
 */
export type GoalId = string

/**
 * A goal as the UI sees it: the saved key plus whatever the current catalog knows
 * about it. `target: None` means "not resolvable right now" — game not installed, or
 * an id a patch has removed: the goal stays visible and is removed by its `key`,
 * which is the only thing the database holds.
 */
export type GoalView = {
  id: GoalId
  key: TargetKey
  target: UnlockTarget | null
  createdUnix: number
  note: string | null
}

export type PlanStep = { goal: GoalId; node: UnlockNode; done: boolean }

export type PlanExpansion =
  { kind: 'stub' } | { kind: 'computed'; steps: Array<PlanStep> }

/**
 * The plan degrades and says why. `store_available` is derived from the absence of
 * `StoreUnavailable`: the UI uses it as a gate and reads the diagnostics for the text.
 * `UnreadableGoal` and `UnresolvedGoal` carry the id, so the UI can offer to remove them.
 * `NoCatalog` arrives once, not once per goal.
 */
export type PlanDiagnostic =
  | { kind: 'storeUnavailable'; reason: StoreReason }
  | { kind: 'unreadableGoal'; id: GoalId }
  | { kind: 'noCatalog' }
  | { kind: 'unresolvedGoal'; id: GoalId }

export type PlanView = {
  goals: Array<GoalView>
  expansion: PlanExpansion
  /**
   * What couldn't be read from the plan: one row per unreadable goal.
   */
  diagnostics: Array<PlanDiagnostic>
  /**
   * `false` when `store` failed to open: goals can't be seen or added, and the UI
   * must say so instead of showing an empty list.
   */
  storeAvailable: boolean
}

/**
 * Fieldless: a bare string.
 */
export const SectionKind = {
  Effects: 'effects',
  Notes: 'notes',
  Synergies: 'synergies',
  Interactions: 'interactions',
  Bugs: 'bugs',
  Behavior: 'behavior',
  ChampionVersions: 'championVersions',
  DamageScaling: 'damageScaling',
  Strategies: 'strategies',
  Difficulty: 'difficulty',
  Reward: 'reward',
  Unlockable: 'unlockable',
} as const
export type SectionKind = (typeof SectionKind)[keyof typeof SectionKind]

export const Style = {
  Plain: 'plain',
  Bold: 'bold',
  Italic: 'italic',
} as const
export type Style = (typeof Style)[keyof typeof Style]

export const Dlc = {
  Rebirth: 'rebirth',
  Afterbirth: 'afterbirth',
  AfterbirthPlus: 'afterbirthPlus',
  Repentance: 'repentance',
  RepentancePlus: 'repentancePlus',
} as const
export type Dlc = (typeof Dlc)[keyof typeof Dlc]

/**
 * The identity of a wiki element: what a `ref` points to, and what a page load accepts.
 */
export type Target =
  | { kind: 'item'; id: number }
  | { kind: 'trinket'; id: number }
  | { kind: 'character'; id: number }
  | { kind: 'achievement'; id: number }
  | { kind: 'challenge'; number: number }
  | { kind: 'entity'; id: number; variant: number; subtype: number }
  | { kind: 'transformation'; id: number }
  | { kind: 'stage'; name: string }
  | { kind: 'room'; name: string }
  | { kind: 'concept'; name: string }

export type Inline =
  | { kind: 'text'; text: string; style: Style }
  | { kind: 'ref'; target: Target; label: string }
  | { kind: 'concept'; page: string; label: string }
  | { kind: 'edition'; only: Array<Dlc>; inline: Array<Inline> }

export type ListItem = {
  inline: Array<Inline>
  /**
   * The lists nested under the item.
   */
  children: Array<Block>
}

export type Block =
  | { kind: 'paragraph'; inline: Array<Inline> }
  | { kind: 'list'; ordered: boolean; items: Array<ListItem> }
  | {
      kind: 'table'
      header: Array<Array<Inline>>
      rows: Array<Array<Array<Inline>>>
    }
  | { kind: 'heading'; level: number; inline: Array<Inline> }

/**
 * Which of the wiki's two collectible templates the page used. Fieldless, so a bare
 * camelCase string like `SectionKind` and `Style`.
 *
 * It is deliberately NOT `catalog`'s three-way item kind. The wiki has exactly two
 * templates and no familiar one, so a familiar is written with the passive template: this
 * type reports which template was read, and claims nothing about what the item is. A
 * `bool` would have been worse than either — `activated: false` would silently mean both
 * "passive" and "familiar".
 */
export const CollectibleTemplate = {
  Passive: 'passive',
  Activated: 'activated',
} as const
export type CollectibleTemplate =
  (typeof CollectibleTemplate)[keyof typeof CollectibleTemplate]

export type Infobox =
  | {
      kind: 'item'
      /**
       * The pickup quote. Inline, not a string: 78 of 719 carry edition markup
       * (`Boomerang tears {{dlc|r|+ DMG up + luck down}}`), and read as raw text they
       * put wikitext on screen. Flattened, it is `items.xml`'s `description` attribute —
       * which `wiki_agrees_with_catalog` checks rather than assumes.
       */
      quote: Array<Inline>
      /**
       * From the template name: the wiki has `infobox passive collectible` and
       * `infobox activated collectible`, and until 2026-09-13 we merged the two.
       */
      template: CollectibleTemplate
      /**
       * `-1..=4`, as `catalog::Metadata::quality`.
       */
      quality: number | null
      /**
       * The game's vocabulary, open by nature: a closed enum breaks the day it grows.
       */
      tags: Array<string>
      /**
       * Not a number. The real values include `unlimited`, `one time`, `4s` and
       * `{{dlcalt|6|r=4}}`; a numeric parse would discard about a third of them.
       */
      recharge: Array<Inline>
      /**
       * Not a number either: 36 of the 56 real `devil price` values are per-edition.
       */
      devilPrice: Array<Inline>
      shopPrice: Array<Inline>
      /**
       * What the wiki says about the pools. Present on only 45 of 720 pages: the
       * game's `itempools.xml` is the source that knows them all.
       */
      pools: Array<Inline>
    }
  | {
      kind: 'trinket'
      quote: Array<Inline>
      tags: Array<string>
      pools: Array<Inline>
    }
  | {
      kind: 'achievement'
      requirements: Array<Inline>
      /**
       * Caveats on the requirement ("Possession of The Polaroid is required…"). An
       * achievement is a row on a storage page and carries no sections of its own, so
       * this is the only prose it has beyond `description` and `requirements`.
       */
      notes: Array<Inline>
      /**
       * The thing this achievement unlocks. It does NOT rise to `Entry`: it points the
       * opposite way from `unlocked_by`, and putting the two in one place is a trap.
       */
      unlocks: Target | null
    }
  | {
      kind: 'boss'
      baseHp: number | null
      /**
       * Inline, not a number: the two real values are per-stage notes, not a scalar.
       */
      stageHp: Array<Inline>
      /**
       * The bestiary variant, when the infobox states one.
       */
      variant: number | null
      environment: Array<Inline>
      pool: Array<Inline>
    }
  | {
      kind: 'challenge'
      blindfolded: boolean
      hasShops: boolean
      hasTreasureRooms: boolean
      items: Array<Inline>
      trinkets: Array<Inline>
      pickups: Array<Inline>
      health: Array<Inline>
      curse: Array<Inline>
      goal: Array<Inline>
      /**
       * The character the challenge is played as, when it forces one.
       */
      character: Target | null
      unlocks: Target | null
    }
  | {
      kind: 'transformation'
      /**
       * How many of `contributors` are needed. `None` when the page does not say it in a
       * form we can read — never defaulted to three, which is what every page that does
       * say it says, and therefore what a wrong default would be invisible against.
       */
      requires: number | null
      /**
       * The items and trinkets that count, in page order, deduplicated. The union of the
       * infobox's `items` and the body's own tables: each loses something the other has.
       */
      contributors: Array<Target>
      /**
       * What the transformation acts on ("Isaac's bums"). Kept because the Cargo table
       * declares it, and `no_silent_parameter` fails on a parameter that is neither a
       * field nor deliberately ignored.
       */
      target: Array<Inline>
    }
  | {
      kind: 'character'
      health: Array<Inline>
      damage: string
      /**
       * The fire-rate stat. It was the only one of the six the type did not carry.
       */
      tears: string
      range: string
      speed: string
      luck: string
      shotSpeed: string
      pickups: Array<Inline>
      collectibles: Array<Inline>
      /**
       * The character this one is a variant of (Lazarus Risen's Lazarus, Tainted's base).
       */
      parent: Target | null
    }

export type Section = { kind: SectionKind; blocks: Array<Block> }

/**
 * A wiki page reduced to what's needed: the infobox and the text sections that are kept.
 */
export type Entry = {
  title: string
  /**
   * Wiki revision the page was read from: says how stale the data is.
   */
  revid: number
  /**
   * The infobox's summary line. Plain text for achievements, wikitext everywhere else:
   * both arrive as inline so the frontend has one shape and no switch on the kind.
   */
  description: Array<Inline>
  /**
   * The editions the **infobox** says the entry exists in, in release order. Empty when
   * the parameter is absent, which is the wiki's "no restriction" and not "it exists
   * nowhere"; a page that writes the restriction out as `n` lists all five.
   *
   * The parameter holds a code, and a code names a **range**: `r` is "added in
   * Repentance", so it lists Repentance and Repentance+. Read one code at a time it came
   * out too narrow on 1078 of the 1083 pages that carry one, until 2026-09-15.
   *
   * Same source as the Cargo tables' `dlc` integer, which is that code already resolved
   * to its bitmask (1 Rebirth, 2 Afterbirth, 4 Afterbirth+, 8 Repentance,
   * 16 Repentance+); the two agree row for row on the collectible table. This field
   * still does not read it, because a page has an infobox whether or not it has a Cargo
   * row.
   */
  dlc: Array<Dlc>
  /**
   * What the wiki states has to be unlocked first. `None` means "the wiki does not state
   * one", NEVER "it is free from the start": that answer belongs to `catalog` and `graph`.
   */
  unlockedBy: Target | null
  infobox: Infobox
  sections: Array<Section>
}

/**
 * Why the embedded dataset failed to load. Fieldless: a bare string.
 */
export const WikiMissingReason = {
  SchemaMismatch: 'schemaMismatch',
  Malformed: 'malformed',
} as const
export type WikiMissingReason =
  (typeof WikiMissingReason)[keyof typeof WikiMissingReason]

/**
 * A game patch, as the wiki knows it.
 */
export type PatchView = { number: string; date: string }

/**
 * Per-type entry counts in the embedded dataset.
 */
export type WikiCounts = {
  items: number
  trinkets: number
  achievements: number
  bosses: number
  challenges: number
  characters: number
  transformations: number
}

/**
 * The state of the wiki dataset: what the verification screen shows, and the basis
 * for saying "is it worth updating?".
 */
export type WikiInfo =
  | {
      kind: 'loaded'
      snapshotAt: string
      lastKnownPatch: PatchView | null
      counts: WikiCounts
      unresolved: number
      unknownTemplates: number
      /**
       * `None` when the game's installation date isn't known: there's no way to
       * tell whether the snapshot is behind.
       */
      gameNewerThanSnapshot: boolean | null
    }
  | { kind: 'missing'; reason: WikiMissingReason }

/**
 * One page of the dataset: its identity, its own title, and the link to its figure when
 * the catalog draws one.
 */
export type WikiPageRef = {
  target: Target
  title: string
  iconUrl: string | null
}

/**
 * Every page the dataset has, once per window (spec 3.5, Decision 2): what the tab labels,
 * the category lists and the icon of every reference inside a page are read from.
 */
export type WikiIndex = { info: WikiInfo; pages: Array<WikiPageRef> }

/**
 * Where a target stands in the profile. Fieldless: a bare string.
 */
export const ProgressMark = {
  Done: 'done',
  Pending: 'pending',
  Unknown: 'unknown',
  None: 'none',
} as const
export type ProgressMark = (typeof ProgressMark)[keyof typeof ProgressMark]

/**
 * What the answer couldn't take into account. Fieldless: a bare string.
 */
export const SearchDiagnostic = {
  NoProfile: 'noProfile',
  NoCatalog: 'noCatalog',
  NoWiki: 'noWiki',
  NoAchievementSection: 'noAchievementSection',
  NoCollectionSection: 'noCollectionSection',
} as const
export type SearchDiagnostic =
  (typeof SearchDiagnostic)[keyof typeof SearchDiagnostic]

/**
 * Why the hit matched, in the words the row shows. Tagged: two of the three carry data.
 */
export type SearchMatch =
  | { kind: 'title' }
  | { kind: 'condition'; text: string }
  | {
      kind: 'section'
      section: SectionKind
      before: string
      matched: string
      after: string
    }

export type SearchHit = {
  target: Target
  title: string
  iconUrl: string | null
  /**
   * The dataset has this page: a Wiki destination exists for the hit.
   */
  hasPage: boolean
  match: SearchMatch
  progress: ProgressMark
}

/**
 * A ranked answer. `total` is how many documents matched before the limit: the screen says
 * "300 of N" from it, and the palette's last row counts with it.
 */
export type SearchView = {
  query: string
  hits: Array<SearchHit>
  total: number
  diagnostics: Array<SearchDiagnostic>
}

/**
 * A queue row is an **achievement**, not a target: wanting Tainted Lost and wanting the
 * achievement that unlocks it are the same wish seen from two sides.
 */
export type QueueRow = {
  /**
   * The same node the Unlock screen draws, so the two can never disagree.
   */
  node: UnlockNode
  /**
   * You asked for this one, for itself.
   */
  wanted: boolean
  /**
   * The wanted achievements whose chain passes through this row.
   */
  origins: Array<number>
  /**
   * Prerequisites this row still needs that are **not** in the queue.
   */
  stepsNotQueued: number
}

/**
 * Every way a row can be absent, said out loud. `Unreadable` and an empty queue are
 * different things, and so are `Completed` and a row that just vanished.
 */
export type QueueDiagnostic =
  | { kind: 'storeUnavailable'; reason: StoreReason }
  | { kind: 'unreadable' }
  | { kind: 'completed'; count: number; wanted: Array<number> }
  | { kind: 'unresolved'; achievement: number }
  | { kind: 'goalsPending'; count: number }
  | { kind: 'noCatalog' }

export type QueueView = {
  rows: Array<QueueRow>
  diagnostics: Array<QueueDiagnostic>
  /**
   * `false` when `store` won't open: the queue can't be seen or changed, and the UI
   * says so instead of showing an empty list.
   */
  storeAvailable: boolean
}

/**
 * Where a run came from. Tagged, because one variant carries a name and the other cannot.
 */
export type RunSource = { kind: 'live' } | { kind: 'session'; name: string }

/**
 * How a run ended, as the UI draws it. `Open` is not a failure and must never be drawn as one.
 */
export type RunOutcomeView =
  | { kind: 'won'; ending: string }
  | { kind: 'died'; killer: string }
  | { kind: 'abandoned' }
  | { kind: 'open' }

/**
 * An item in a run. `name` is `None` without a catalog.
 */
export type RunItemRef = {
  id: number
  name: string | null
  /**
   * The sprite from the user's own copy of the game, `None` without it. A run draws its
   * items the way every other list does; the id stays, because a picture nobody can serve
   * must not take the place of the one thing we know.
   */
  iconUrl: string | null
}

/**
 * One run.
 */
export type RunView = {
  source: RunSource
  /**
   * The position in its own source. A run is `(source, ordinal)`.
   */
  ordinal: number
  /**
   * `None` when no item line ever named the character: it is not in the seed line.
   */
  character: string | null
  /**
   * The character the log states by id — `Initialized player with Variant 0 and Subtype N`.
   * It tells a Tainted form from its base, which the name cannot: the game gives both the
   * same one.
   */
  characterId: number | null
  seedWords: string
  /**
   * The game called this run online. The only free discriminator we have for co-op.
   */
  online: boolean
  outcome: RunOutcomeView
  floors: number
  startingItems: Array<RunItemRef>
  collected: Array<RunItemRef>
  heldActive: RunItemRef | null
  achievements: Array<number>
}

/**
 * How many runs, and how they ended.
 */
export type RunTotals = {
  runs: number
  won: number
  died: number
  abandoned: number
  open: number
}

/**
 * Every way the archive can be less than whole, said out loud.
 */
export type RunsDiagnostic =
  | { kind: 'noLogFolder' }
  | { kind: 'storeUnavailable'; reason: StoreReason }
  | { kind: 'unreadableEvents'; count: number }
  | { kind: 'noCatalog' }

export type RunsView = {
  runs: Array<RunView>
  totals: RunTotals
  diagnostics: Array<RunsDiagnostic>
}

/**
 * A room as the screen paints it.
 */
export const RoomKindView = {
  Start: 'start',
  Normal: 'normal',
  Boss: 'boss',
  Treasure: 'treasure',
  Shop: 'shop',
  Curse: 'curse',
  Challenge: 'challenge',
  Sacrifice: 'sacrifice',
  Arcade: 'arcade',
  Library: 'library',
  Miniboss: 'miniboss',
  Secret: 'secret',
  SuperSecret: 'superSecret',
  UltraSecret: 'ultraSecret',
} as const
export type RoomKindView = (typeof RoomKindView)[keyof typeof RoomKindView]

export const TargetView = {
  Secret: 'secret',
  SuperSecret: 'superSecret',
  UltraSecret: 'ultraSecret',
} as const
export type TargetView = (typeof TargetView)[keyof typeof TargetView]

/**
 * One rule behind a candidate, with the sentence it was read from.
 */
export type AppliedRule = { id: string; quote: string; url: string }

export type FloorCandidate = {
  cell: number
  neighbours: number
  /**
   * Its place in the preference order the cited rule states; 0 is that rule's first.
   */
  rank: number
  applied: Array<AppliedRule>
}

export type FloorUnresolved = {
  rule: string
  note: string
  quote: string
  url: string
}

export type FloorSolutionView = {
  target: TargetView
  candidates: Array<FloorCandidate>
  unresolved: Array<FloorUnresolved>
}

/**
 * Everything that stops the screen from answering, said out loud. None of them may be drawn
 * as "there is nowhere for a secret room": that is an answer, and these are the absence of one.
 */
export type FloorDiagnostic =
  | { kind: 'gridEmpty' }
  | { kind: 'noStartRoom' }
  | { kind: 'rulesUnreadable'; reason: string }
  | { kind: 'gridMalformed'; cells: number }

export type FloorView = {
  solutions: Array<FloorSolutionView>
  /**
   * How many cells are painted. A count, not a fraction: nothing here knows how many rooms
   * the floor has.
   */
  painted: number
  diagnostics: Array<FloorDiagnostic>
}

/**
 * One achievement this run could open, and how much it opens in turn: the graph already
 * counts that for Unlock, and a run is worth more when what it gives unlocks more.
 */
export type LiveAchievement = { achievement: AchievementRef; fanOut: number }

/**
 * One cell of the matrix, and what beating it with this character would open.
 */
export type LiveOpen = {
  character: number
  characterName: string
  column: MarkColumnView
  level: MarkLevelView
  achievements: Array<LiveAchievement>
}

/**
 * One character's row of the completion matrix, as Live draws it: what this character has
 * taken, and what it still has to. The screen puts it beside what the run could open, which
 * is the only place in the app where the two questions meet.
 */
export type LiveMarkRow = {
  character: string
  headUrl: string | null
  cells: Array<Cell>
  /**
   * Cells with nothing taken yet. Not a percentage: an unread cell is not a zero, and the
   * matrix already refuses to average the two (B22/B23).
   */
  missing: number
}

/**
 * The rows Live shows, with the columns they are read against.
 */
export type LiveMarks = {
  bosses: Array<string>
  art: Array<MarkArtView>
  rows: Array<LiveMarkRow>
}

/**
 * Everything that stops this screen from answering, said out loud. None of them may be
 * drawn as "this run opens nothing": that is an answer, and these are the absence of one.
 */
export type LiveDiagnostic =
  | { kind: 'noRun' }
  | { kind: 'characterNotNamed' }
  | { kind: 'unknownCharacter'; name: string }
  | { kind: 'ambiguousCharacter'; name: string; forms: number }
  | { kind: 'noGraph' }
  | { kind: 'noProfile' }

export type LiveView = {
  run: RunView | null
  /**
   * The completion row of the character being played — two rows when the name reaches two
   * forms. `None` without a profile or without the sections that hold the marks.
   */
  marks: LiveMarks | null
  /**
   * Grouped by the cell it needs: "beat Mom's Heart with Cain" once, with everything it
   * opens under it, instead of the same boss read five times.
   */
  opens: Array<LiveOpen>
  diagnostics: Array<LiveDiagnostic>
}

/**
 * What stands between the item and a run. Tagged: three of the four variants carry data.
 */
export type LockView =
  | { kind: 'free' }
  | {
      kind: 'unlocked'
      achievement: number
      text: string | null
      /**
       * The achievement's wiki page. `None` means the dataset has no page for it: the
       * name shows and does not link. Never "no achievement".
       */
      page: Target | null
    }
  | {
      kind: 'locked'
      achievement: number
      text: string | null
      page: Target | null
    }
  | {
      kind: 'unknown'
      achievement: number
      text: string | null
      page: Target | null
    }

export type CollectionItem = {
  id: number
  kind: ItemKindView
  name: string
  iconUrl: string | null
  quality: number | null
  pools: Array<string>
  origin: OriginView | null
  /**
   * `None` when section 4 wasn't read, or the save has no slot for this id: unread is
   * never "not in the collection".
   */
  inCollection: boolean | null
  lock: LockView
}

export type CollectionTotals = {
  /**
   * Section 4's length; 0 when it wasn't read.
   */
  slots: number
  items: number
  inCollection: number
}

export type CollectionDiagnostic =
  | { kind: 'noCatalog' }
  | { kind: 'noCollectionSection' }
  | { kind: 'noAchievementSection' }
  | { kind: 'itemsBeyondSlots'; count: number }

export type CollectionView = {
  items: Array<CollectionItem>
  /**
   * The pools any listed item belongs to, each once, in the catalog's order.
   */
  pools: Array<string>
  totals: CollectionTotals
  diagnostics: Array<CollectionDiagnostic>
}

/**
 * Tagged, because `Blocked` carries the gates it waits for — the repo's rule, and the shape
 * `LockView` already has.
 */
export type ChallengeStateView =
  | { kind: 'done' }
  | { kind: 'available' }
  | { kind: 'blocked'; missing: Array<number> }
  | { kind: 'unknown' }

export type RewardView = {
  achievement: number
  text: string | null
  iconUrl: string | null
  page: Target | null
  /**
   * Whether the save says it is earned. `None` when section 1 wasn't read: unread is never
   * "not earned".
   */
  done: boolean | null
}

export type ChallengeRow = {
  number: number
  name: string
  state: ChallengeStateView
  /**
   * What finishing it grants. Empty for the challenges that grant nothing.
   */
  rewards: Array<RewardView>
  /**
   * The character the wiki says it forces. `None` is "the dataset has no page for this
   * challenge, or the page names no character" — never "any character".
   */
  character: Target | null
  /**
   * That character's name, read from **its own** wiki page's title. The reference the
   * infobox carries is an id, and a screen cannot name an id: without this the row would
   * have to invent a word. `None` when the dataset has no page for that character.
   */
  characterName: string | null
  goal: Array<Inline> | null
  /**
   * `None` when there is no page. It must not draw as "not blindfolded".
   */
  blindfolded: boolean | null
  page: Target | null
}

export type ChallengeTotals = {
  /**
   * Section 7's own length; 0 when it wasn't read. Never the constant 46.
   */
  slots: number
  challenges: number
  done: number
}

export type ChallengesDiagnostic =
  | { kind: 'noCatalog' }
  | { kind: 'noChallengesSection' }
  | { kind: 'noAchievementSection' }
  | { kind: 'noWiki' }

export type ChallengesView = {
  challenges: Array<ChallengeRow>
  totals: ChallengeTotals
  diagnostics: Array<ChallengesDiagnostic>
}

/**
 * Persisted settings. The type and its serialization live here;
 * reading and writing the file live in the app crate.
 */
export type Settings = {
  activeProfileId: ProfileId | null
  /**
   * The interface's size as a percentage. Public because it has to serialize, but read
   * through `scale()`: the field is whatever the file said.
   */
  scale: number
  /**
   * Closing the last window leaves the app in the notification area instead of ending it.
   * **On by default**: it is the behaviour, and the switch exists for whoever doesn't want
   * an app in their tray.
   */
  stayInBackground: boolean
  /**
   * A window born with nothing owed to it opens on the tabs of the last session.
   */
  resumeTabs: boolean
  /**
   * Whether the one-time "it's still running" notice has been shown. Written by the app,
   * never shown to the user.
   */
  backgroundNoticeShown: boolean
}

/**
 * Why the switch cannot be offered.
 *
 * No variant carries a field, so this is a **bare camelCase string** on the wire and the
 * TypeScript mirrors it as a union of values — the rule `CLAUDE.md` states with zero
 * exceptions. The design asked for it tagged by analogy with `SettingsReason` and
 * `StoreReason`, which are tagged because a variant of each carries data; this one has none,
 * and a tag would add a key per answer to say what the value already says.
 */
export const AutostartReason = {
  NotSupported: 'notSupported',
  RegistryUnreadable: 'registryUnreadable',
} as const
export type AutostartReason =
  (typeof AutostartReason)[keyof typeof AutostartReason]

/**
 * Why turning the switch did not take. Two answers because they are two different things for
 * the user to do, and the app can tell them apart: the plugin says whether the write itself
 * was refused, and the registry says whether it survived.
 *
 * Fieldless, so a bare camelCase string on the wire, like [`AutostartReason`] — and a type of
 * its own rather than more variants on that one, because the two sets never meet: the view
 * answers why the switch cannot be *offered*, this answers why it would not *move*, and a
 * `switch` over either should not carry branches that cannot happen.
 */
export const AutostartFailure = {
  WriteRefused: 'writeRefused',
  WriteIgnored: 'writeIgnored',
} as const
export type AutostartFailure =
  (typeof AutostartFailure)[keyof typeof AutostartFailure]

/**
 * The switch, as the registry answers it right now.
 *
 * Read when the Background screen mounts and not once at startup: the app sits in the tray for
 * days, and the Startup tab can have changed underneath it.
 */
export type AutostartView = {
  /**
   * What the registry says, never what was asked for.
   */
  enabled: boolean
  /**
   * `None` when the switch can be offered. The design had a bare `available: bool` here,
   * which made a development build and a registry that would not answer the same answer
   * with two different causes.
   */
  unavailable: AutostartReason | null
}
